### ISSUE TITLE
Server part missing

### ISSUE THREAD

**Issue by jsarenik** [petertodd/dust-b-gone#4]
Thank you for this, @petertodd! I just learned about `dust-b-gone` on #bitcon IRC channel.
In the source code I do not see the server part. Could you please release it with some short
description as well so that someone else can run the server?

**Comment by petertodd** [comment]
The server part was literally just `socat` piped to a file. There's nothing to release! I forget the exact options I used. But they should be simple enough to figure out from the man page.

**Comment by jsarenik** [comment]
Yes. That makes sense. Thank you!

In the meantime this is my writeup on how one can get rid of the dust on their own: https://bin.bublina.eu.org/?b8828378e4144240#6cz3baxbPQ6RizezjY45fduFPmJkngwVspgPxbuxJGmS

And here is an example on testnet: https://blockstream.info/testnet/address/tb1qqg24ah8qre3uzutq2sju9jz70xnmvjsq5r67uy
