### ISSUE TITLE
the server that dust-b-gone sent dust to isn't running right now

### ISSUE THREAD

**Issue by librem5** [petertodd/dust-b-gone#6]
Hello, can you provide the server backend?

**Comment by petertodd** [comment]
On Sat, Apr 27, 2024 at 09:15:49AM -0700, librem5 wrote:
> Hello, can you provide the server backend?

I didn't get enough interest for it to be worth keeping the server backend up.

**Comment by librem5** [comment]
sure, ofc i understand, but you can give some code from server, and i can run it on my server for other ppl, just delete sensitive data  and put server code here, if that possible

**Comment by petertodd** [comment]
On Sun, Apr 28, 2024 at 01:06:31PM -0700, librem5 wrote:
> sure, ofc i understand, but you can give some code from server, and i can run it on my server for other ppl, just delete sensitive data  and put server code here, if that possible

The "server" as just running socat with the right config options to append
incoming lines to a text file.

**Comment by librem5** [comment]
thx
